// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels(in *jlexer.Lexer, out *URLsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "links":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Links = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.Links)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "links_num":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Num = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels(out *jwriter.Writer, in URLsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"links\":"
		out.RawString(prefix[1:])
		if in.Links == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Links {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"links_num\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Num))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URLsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URLsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URLsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URLsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels(l, v)
}
func easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels1(in *jlexer.Lexer, out *URLsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "links":
			if in.IsNull() {
				in.Skip()
				out.Links = nil
			} else {
				in.Delim('[')
				if out.Links == nil {
					if !in.IsDelim(']') {
						out.Links = make([]string, 0, 4)
					} else {
						out.Links = []string{}
					}
				} else {
					out.Links = (out.Links)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.Links = append(out.Links, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels1(out *jwriter.Writer, in URLsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"links\":"
		out.RawString(prefix[1:])
		if in.Links == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Links {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URLsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URLsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URLsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URLsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels1(l, v)
}
func easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels2(in *jlexer.Lexer, out *PDFRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "links_list":
			if in.IsNull() {
				in.Skip()
				out.Nums = nil
			} else {
				in.Delim('[')
				if out.Nums == nil {
					if !in.IsDelim(']') {
						out.Nums = make([]uint64, 0, 8)
					} else {
						out.Nums = []uint64{}
					}
				} else {
					out.Nums = (out.Nums)[:0]
				}
				for !in.IsDelim(']') {
					var v6 uint64
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = uint64(in.Uint64())
					}
					out.Nums = append(out.Nums, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels2(out *jwriter.Writer, in PDFRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"links_list\":"
		out.RawString(prefix[1:])
		if in.Nums == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Nums {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.Uint64(uint64(v8))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PDFRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PDFRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PDFRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PDFRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels2(l, v)
}
func easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels3(in *jlexer.Lexer, out *FileStore) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Data":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(Data)
				for !in.IsDelim('}') {
					key := uint64(in.Uint64Str())
					in.WantColon()
					var v9 URLsKit
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v9 = make(URLsKit)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v10 bool
							if in.IsNull() {
								in.Skip()
							} else {
								v10 = bool(in.Bool())
							}
							(v9)[key] = v10
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Data)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		case "Num":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Num = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels3(out *jwriter.Writer, in FileStore) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix[1:])
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v11First := true
			for v11Name, v11Value := range in.Data {
				if v11First {
					v11First = false
				} else {
					out.RawByte(',')
				}
				out.Uint64Str(uint64(v11Name))
				out.RawByte(':')
				if v11Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v12First := true
					for v12Name, v12Value := range v11Value {
						if v12First {
							v12First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v12Name))
						out.RawByte(':')
						out.Bool(bool(v12Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"Num\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Num))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileStore) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileStore) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComSTurchinskiyUrlsavailabilityModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileStore) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileStore) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComSTurchinskiyUrlsavailabilityModels3(l, v)
}
